### ISSUE TITLE
Full view export

### ISSUE THREAD

**Issue by paulJordaan** [jeremytammik/SvgExport#1]
Hi Jeremy, thank you for a very informative blog. 

I would like to extend on the add-in to support the full export of building plans to .svg files in order to  view them in a node.js project. Is this possible? Is there any pointers you could perhaps give me on how to achieve this. I am relatively new to revit add-in development.

Thanks

**Comment by jeremytammik** [comment]
dear paul, this is absolutely possible. i proved a similar concept with my RoomEditorApp and the associated cloud-based roomedit couchdb database. that does not export full building plans, just the room boundary and furniture and equipment outlines. the cool thing, though, is that you can edit the furniture and equipment location in the cloud-based database via any client on any mobile device and hook it up so the revit database is immediately simultaneously updated. check it out here:

http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.21

**Comment by paulJordaan** [comment]
Thanks for the quick reply. I will take a look at the RoomEditorApp and see
if I can extend on that then.

**Comment by jeremytammik** [comment]
i once started working on exporting the full 2D sheets with the views on them:

http://thebuildingcoder.typepad.com/blog/2014/04/determining-the-size-and-location-of-viewports-on-a-sheet.html

i gave up on that, though...

looking forward to hearing how it goes for you!

good luck!
