### ISSUE TITLE
Update it for 2021?

### ISSUE THREAD

**Issue by JarodSchultz** [jeremytammik/SvgExport#2]
Would love to see this updated for Revit 2021. Have some use cases where it would be nice to export out a SVG from Revit 2021 so I could use the SVG file in other software.

Thanks!

**Comment by jeremytammik** [comment]
I will gladly take a look at this. You are aware that this is a pretty limited export, and you will certainly need to modify it for your own requirements. You have read the blog posts, haven't you? I have completely forgotten what they say, and what this thing actually exports...   :-)

**Comment by jeremytammik** [comment]
done. Enjoy!
